# Generated by Django 3.2.5 on 2021-11-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20210311_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ques_image',
            field=models.ImageField(blank=True, default='defaultt.png', null=True, upload_to=''),
        ),
    ]
