# Generated by Django 3.2.5 on 2021-11-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_question_ques_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ques_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
